# Generated by Django 3.1 on 2020-09-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIMSApplication', '0002_auto_20200916_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=70)),
                ('active', models.BooleanField(default='false')),
            ],
        ),
    ]
